### ISSUE TITLE
Hosting of API docs

### ISSUE THREAD

**Issue by slinkydeveloper** [restatedev/documentation#240]
We should publish API docs for ts, java and kotlin. This entails both figuring out how and then automate it.

```[tasklist]
### Tasks
- [ ] Check how to host API docs on cloudflare
- [ ] https://github.com/restatedev/sdk-typescript/issues/213
- [ ] https://github.com/restatedev/sdk-java/issues/190
- [ ] Publish javadocs as well.
- [ ] Automate on every SDK release the publishing of API docs. Ideally this doesn't require any step on the documentation repo, but everything is executed together with the release of the SDK.
- [ ] Cross-link docs to API docs. This also includes linking relevant class/object docs inline in the documentation.
```
