### ISSUE TITLE
Write CLI docs

### ISSUE THREAD

**Issue by gvdongen** [restatedev/documentation#245]
```[tasklist]
### Tasks
- [ ] https://github.com/restatedev/documentation/issues/248
- [ ] https://github.com/restatedev/documentation/issues/246
- [ ] https://github.com/restatedev/documentation/issues/247
```
