### ISSUE TITLE
Next documentation iteration: umbrella issue

### ISSUE THREAD

**Issue by gvdongen** [restatedev/documentation#265]
This umbrella issue groups issues related to the new iteration of the docs, in which we want to improve the structure, give more context, and have more unified language.

```[tasklist]
### Improving overall structure
- [ ] https://github.com/restatedev/documentation/issues/269
- [ ] https://github.com/restatedev/documentation/issues/266
- [ ] https://github.com/restatedev/documentation/issues/207
- [ ] https://github.com/restatedev/documentation/issues/230
- [ ] https://github.com/restatedev/documentation/issues/295
- [ ] https://github.com/restatedev/documentation/issues/296
```

```[tasklist]
### Giving more context
- [ ] https://github.com/restatedev/documentation/issues/267
- [ ] https://github.com/restatedev/documentation/issues/271
- [ ] https://github.com/restatedev/documentation/issues/185
- [ ] https://github.com/restatedev/documentation/issues/219
- [ ] https://github.com/restatedev/documentation/issues/227
- [ ] #231
- [ ] https://github.com/restatedev/documentation/issues/237
- [ ] https://github.com/restatedev/documentation/issues/238
- [ ] https://github.com/restatedev/documentation/issues/257
```

```[tasklist]
### Making language more uniform
- [ ] https://github.com/restatedev/documentation/issues/69
- [ ] #63
- [ ] https://github.com/restatedev/documentation/issues/272
- [ ] https://github.com/restatedev/documentation/issues/150
- [ ] #151
```

```[tasklist]
### Bugs
- [ ] https://github.com/restatedev/documentation/issues/323
- [ ] https://github.com/restatedev/documentation/issues/343
```
