### ISSUE TITLE
Documentation M1B

### ISSUE THREAD

**Issue by tillrohrmann** [restatedev/documentation#27]
Documentation tasks for the milestone 1B.

```[tasklist]
### Tasks
- [ ] https://github.com/restatedev/documentation/issues/8
- [ ] https://github.com/restatedev/documentation/issues/6
- [ ] https://github.com/restatedev/documentation/issues/7
- [ ] https://github.com/restatedev/documentation/issues/5
- [ ] https://github.com/restatedev/documentation/issues/4
```

**Comment by gvdongen** [comment]
@tillrohrmann Should we close this?
