### ISSUE TITLE
Terminology renaming

### ISSUE THREAD

**Issue by gvdongen** [restatedev/documentation#272]
```[tasklist]
### Tasks
- [ ] https://github.com/restatedev/documentation/issues/274
- [ ] https://github.com/restatedev/documentation/issues/275
- [ ] https://github.com/restatedev/documentation/issues/276
- [ ] https://github.com/restatedev/documentation/issues/277
- [ ] https://github.com/restatedev/documentation/issues/278
- [ ] https://github.com/restatedev/documentation/issues/279
```
