### ISSUE TITLE
Unify docker run commands across OS

### ISSUE THREAD

**Issue by gvdongen** [restatedev/documentation#281]
As mentioned by Stephan on Discord (https://discord.com/channels/1128210118216007792/1195397939099619399/1199489593402212373)
Previously we had two separate commands for MacOS and Linus. The problem was previously that networking was a bit different, MacOS requiring the use of host.docker.internal, which is unavailable on Linux, and Linux directly using the host network, which wasn't  compatible with most MacOS setups.

But we can add `--add-host=host.docker.internal:host-gateway` to the docker command, which seems to make the host.docker.internal address available in all setups.

Those commands here should work on all systems:

`docker run --name restate_dev --rm -p 8080:8080 -p 9070:9070 -p 9071:9071 --add-host=host.docker.internal:host-gateway docker.io/restatedev/restate:latest`

`curl -i -X POST http://localhost:9070/deployments  -H 'content-type: application/json' -d '{"uri": "http://host.docker.internal:9080"}'`

We should update all content to use this
```[tasklist]
### Tasks
- [ ] https://github.com/restatedev/documentation/issues/287
- [ ] https://github.com/restatedev/documentation/issues/286
- [ ] https://github.com/restatedev/documentation/issues/285
- [ ] https://github.com/restatedev/documentation/issues/289
```
