### ISSUE TITLE
Make code snippets tested and compiled on merge and release

### ISSUE THREAD

**Issue by gvdongen** [restatedev/documentation#295]
In-docs code examples should testable and compileable, such that everytime we do a change we cannot merge if the docs are not fixed.

Maybe using
 https://docusaurus.io/docs/markdown-features/react#importing-code-snippets
```[tasklist]
### Tasks
- [ ] https://github.com/restatedev/documentation/issues/318
- [ ] https://github.com/restatedev/documentation/issues/319
- [ ] https://github.com/restatedev/documentation/issues/320
- [ ] https://github.com/restatedev/documentation/issues/321
```
