### ISSUE TITLE
Upgrade SDK

### ISSUE THREAD

**Issue by gvdongen** [restatedev/documentation#33]
Depending on which commits are taken along in the next release of the SDK, we need to:

```[tasklist]
### Tasks
- [x] Update the logs in the tour of Restate tutorial
- [x] Update the docs for the eager state changes
- [x] Update the docs for delayed calls renaming
- [x] Update docs for logging to use new env var
- [x] Update docs for retry side effect utils changes
- [x] https://github.com/restatedev/documentation/issues/41
- [x] https://github.com/restatedev/documentation/issues/39
- [x] https://github.com/restatedev/documentation/issues/40
- [ ] https://github.com/restatedev/documentation/issues/43
- [x] https://github.com/restatedev/documentation/issues/42
- [x] Change logging env var in e2e tests
```
