### ISSUE TITLE
Update documentation wrt to runtime changes

### ISSUE THREAD

**Issue by tillrohrmann** [restatedev/documentation#342]
This is an umbrella issue to collect runtime changes that need to be reflected in the documentation.

```[tasklist]
### Tasks
- [x] Update documentation about new configuration
- [ ] Update options for wiping state
- [ ] Document new CLI options
```
