### ISSUE TITLE
Make the language used throughout the docs more uniform 

### ISSUE THREAD

**Issue by gvdongen** [restatedev/documentation#63]
Different sections were written by different contributors. We should unify the language and commands used.

```[tasklist]
### Tasks
- [ ] https://github.com/restatedev/documentation/issues/141
- [ ] https://github.com/restatedev/documentation/issues/142
- [ ] https://github.com/restatedev/documentation/issues/150
- [ ] https://github.com/restatedev/documentation/issues/151
```
