### ISSUE TITLE
Documentation should be updated to match the style of the website

### ISSUE THREAD

**Issue by gvdongen** [restatedev/documentation#64]
```[tasklist]
### Tasks
- [ ] https://github.com/restatedev/documentation/issues/80
- [ ] https://github.com/restatedev/documentation/issues/81
- [ ] https://github.com/restatedev/documentation/issues/82
```
