### ISSUE TITLE
Documentation sections to be written for private beta release

### ISSUE THREAD

**Issue by gvdongen** [restatedev/documentation#89]
```[tasklist]
### Tasks
- [ ] https://github.com/restatedev/documentation/issues/90
- [ ] https://github.com/restatedev/documentation/issues/92
- [ ] https://github.com/restatedev/documentation/issues/102
- [ ] https://github.com/restatedev/tour-of-restate-typescript/issues/9
```

**Comment by tillrohrmann** [comment]
Seems to be done. Closing it now.
