### ISSUE TITLE
SDK troubleshooting (= Restate SQL introspection)

### ISSUE THREAD

**Issue by gvdongen** [restatedev/documentation#91]
```[tasklist]
### Tasks
- [ ] https://github.com/restatedev/documentation/issues/105
- [ ] https://github.com/restatedev/documentation/issues/103
- [ ] https://github.com/restatedev/documentation/issues/104
```
